services:
  - type: web
    name: ALM-OpAi-
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0

    envVars:
      - key: OPENAI_MODEL
        value: openai/gpt-4-turbo
